spring:
  profiles:
      active: dev
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: true
server:
    context-path: /store
    session-timeout: 1800
    tomcat:
       max-threads: 1000
       min-spare-threads: 30
    port: 8082
    uri-encoding: utf-8
security:
  basic:
    enabled: false
mybatis: 
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.yunda.storee.**.domain
#配置缓存和session存储方式，默认ehcache,可选redis
cacheType: ehcache